### ISSUE TITLE
docs.rs build fails

### ISSUE THREAD

**Issue by dansiemon** [alexforster/libbpf-sys#3] opened 2020-01-14 14:03 UTC
https://docs.rs/crate/libbpf-sys/0.0.6-5/builds

**Comment by alexforster** [comment] 2020-01-14 17:44
Aha, here's the critical missing piece that is _not_ actually mentioned on docs.rs: https://github.com/rust-lang/docs.rs/blob/master/src/docbuilder/metadata.rs#L56

I'll see if adding a `libelf-dev` dep fixes it.

**Comment by dansiemon** [comment] 2020-01-14 20:22
Thanks for looking at this. It breaks the docs.rs build for dependant crates too.

**Comment by alexforster** [comment] 2020-01-14 21:12
Attempt #1 failed, but I've found a wiki article explaining how to reproduce/test locally: https://github.com/rust-lang/docs.rs/wiki/Making-changes-to-the-build-environment

**Comment by alexforster** [comment] 2020-01-14 21:55
The docs.rs team is going to have to add `libelf-dev` and `linux-headers-generic` to the docker container that's used for building crates. I've opened PRs:

https://github.com/rust-lang/crates-build-env/pull/29
https://github.com/rust-lang/crates-build-env/pull/30

**Comment by alexforster** [comment] 2020-01-15 17:20
Looks like it's fixed with the `0.0.6-7` version I just pushed:
 
https://docs.rs/crate/libbpf-sys/

**Closed by alexforster** 2020-01-15 17:20 UTC
Labels: documentation
